apiVersion: v1
kind: PersistentVolume
metadata:
  name: projet-devops-pv
  labels:
    type: projet-devops-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sda1/data"
